spring:
  application:
  name: bigqueryPOC

google:
  cloud:
    project-id: flixsa-422212
    dataset-id: eujoh_testing
    credentials:
      location: ./big-query-flixa.json

server:
  port: 8082

